// <auto-generated />
using System;
using HadasimCovid.Repository.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HadasimCovid.Repository.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240320170029_try")]
    partial class @try
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HadasimCovid.Repository.Entity.CovidDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfPositiveResult")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfRecovery")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMember")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMember");

                    b.ToTable("CovidDetails");
                });

            modelBuilder.Entity("HadasimCovid.Repository.Entity.Member", b =>
                {
                    b.Property<int>("IdMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMember"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBitrth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumBuilding")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tz")
                        .HasColumnType("int");

                    b.HasKey("IdMember");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("HadasimCovid.Repository.Entity.Vaccination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfReceivingVaccine")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMember")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdMember");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("HadasimCovid.Repository.Entity.CovidDetails", b =>
                {
                    b.HasOne("HadasimCovid.Repository.Entity.Member", "Member")
                        .WithMany()
                        .HasForeignKey("IdMember");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("HadasimCovid.Repository.Entity.Vaccination", b =>
                {
                    b.HasOne("HadasimCovid.Repository.Entity.Member", "Member")
                        .WithMany()
                        .HasForeignKey("IdMember");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
